### obtener todos los categorias
GET http://localhost:3000/api/categories


### crear un nuevo categoria
# @name createCategory
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Postres"
}
### obtengo un categoria especifico
### ID 
@id = {{createCategory.response.body.data.id}}
GET http://localhost:3000/api/categories/{{id}}

### modificar un usuario (PUT - idempotente, se modifican TODOS los elementos posibles)
PUT http://localhost:3000/api/categories/66da39eed3173d2a2c1944d9
Content-Type: application/json

{
    "name": "BebidasUpdated",
    "catId": "001"
}


### borrar un categorias
DELETE http://localhost:3000/api/categories/672d4aa6dda5ebf5cf0b7e6a

