### get all
GET http://localhost:3000/api/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDYxMjkzMTMsImV4cCI6MTc0NjEzMjkxM30.H3G2OwMiiuMt5RAa8Idg_bVCxpCbakFDhfx6Pcjbqxs
### crear reservation
POST http://localhost:3000/api/reservations
Content-Type: application/json

{ 
  "state": "Pending",
  "user": "672d4f8bb48ca087afa73e85",
  "people": 5,
  "datetime": "2024-11-24T20:00:00Z"
}
### update
PUT http://localhost:3000/api/reservations/673b8a854bd9c50be408e958
Content-Type: application/json

{"state": "Completed"}
### get one
GET http://localhost:3000/api/reservations/673b8a854bd9c50be408e958

### delete
DELETE http://localhost:3000/api/reservations/68098f57ce01c5af8deb1812
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDYxMjkzMTMsImV4cCI6MTc0NjEzMjkxM30.H3G2OwMiiuMt5RAa8Idg_bVCxpCbakFDhfx6Pcjbqxs



