### get all
GET http://localhost:3000/api/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDYxMjk5MTMsImV4cCI6MTc0NjEzMzUxM30.sNu_A5z7IC3IHZ0Whtk-brpPgWNkQ5PzSLpmkxG0ZD8
### crear reservation
POST http://localhost:3000/api/reservations
Content-Type: application/json

{ 
  "state": "Pending",
  "user": "672d4f8bb48ca087afa73e85",
  "people": 5,
  "datetime": "2024-11-24T20:00:00Z"
}
### update
PUT http://localhost:3000/api/reservations/673b8a854bd9c50be408e958
Content-Type: application/json

{"state": "Completed"}
### get one
GET http://localhost:3000/api/reservations/673b8a854bd9c50be408e958

### delete
DELETE http://localhost:3000/api/reservations/6813d421ae9dbf0e77498879
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDYxMjk5MTMsImV4cCI6MTc0NjEzMzUxM30.sNu_A5z7IC3IHZ0Whtk-brpPgWNkQ5PzSLpmkxG0ZD8
###


