### obtener todos los users
GET http://localhost:3000/api/users


### crear un nuevo user
# @name createUser
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "dni": "27316617",
    "firstName": "German",
    "lastName": "Baro",
    "userType": "Admin"
}
### ID 
@id = {{createUser.response.body.data.id}}
### obtengo un user especifico
GET http://localhost:3000/api/users/{{id}}

### modificar un usuario (PUT - idempotente, se modifican TODOS los elementos posibles)
PUT http://localhost:3000/api/users/66d8efd9f97ea117d363ce7c
Content-Type: application/json

{
    "firstName": "Abril",
    "lastName": "Carballo",
    "userType": "Waiter"
}


### borrar un user
DELETE http://localhost:3000/api/users/66d9093d13851e7f75dccac8
