### obtener todos los users
GET http://localhost:3000/api/users
### obtengo un user especifico
GET http://localhost:3000/api/users/6654e55b3dfa75e545bfb4b8

### crear un nuevo user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "dni": "12345678",
    "firstName": "Bautista",
    "lastName": "Alfaro",
    "userType": "Admin"
}

### modificar un usuario (PUT - idempotente, se modifican TODOS los elementos posibles)
PUT http://localhost:3000/api/users/6654f6355489707b63870a31
Content-Type: application/json

{
    "firstName": "Bautista Puto",
    "lastName": "Alfaro",
    "userType": "Waiter"
}

### modificar un usuario (PATCH - modificacion parcial)
PATCH http://localhost:3000/api/users/6654e55b3dfa75e545bfb4b8
Content-Type: application/json

{
    "userType": "Waiter"
}

### borrar un user
DELETE http://localhost:3000/api/users/6654e55b3dfa75e545bfb4b8