### obtener todos los users

GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGNjMzY4NzM5NGE2YzIxNjkzMGU1NiIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NTUwMzcyNDUsImV4cCI6MTc1NTA0MDg0NX0.HtwLUwlUnDvEjuIJQQRtV5PEy_yv1PE9xhbRUwrhVWM


### crear un nuevo user
# @name createUser
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstName": "Facundo",
  "lastName": "Cantaberta",
  "dni": "43349481",
  "userType": "Admin",
  "email": "cantabertafacus@gmail.com",
  "password": "miContraseñaSegura",
  "address": "Santiago 427, Rosario, Argentina"
}

### Crear un nuevo usuario Admin
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstName": "Facundo",
  "lastName": "Cantaberta",
  "dni": "43349482",
  "userType": "Admin",
  "email": "soyadmin@gmail.com",
  "password": "12345678",
  "address": "Santiago 427, Rosario, Argentina"
}

### Crear un nuevo usuario Mozo
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Maria",
  "lastName": "Pazzzzzzz",
  "dni": "42249482",
  "userType": "Mozo",
  "email": "maria@gmail.com",
  "password": "12345678",
  "address": "Santiago 427, Rosario, Argentina"
}
### Crear un nuevo usuario Cliente
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Maria",
  "lastName": "Paszsxs",
  "dni": "41249482",
  "userType": "Client",
  "email": "maria123@gmail.com",
  "password": "12345678",
  "address": "Santiago 427, Rosario, Argentina"
}



### Registro test
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstName": "Prueba",
  "lastName": "Usuario",
  "dni": "99999999",
  "email": "prueba@registro.com",
  "password": "123456",
  "address": "Calle Test 123",
  "userType": "cliente"
}

### login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "soycliente@gmail.com",
  "password": "Micontra01"
}
###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "cantabertafacus@gmail.com",
  "password": "miContraseñaSegura"
}
### ID 
@id = {{createUser.response.body.data.id}}
### obtengo un user especifico
GET http://localhost:3000/api/users/672d4f6cb48ca087afa73e84
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVjNWMxMDI2NTZmNTY5ZmNkODYzZCIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDU3OTg2MDUsImV4cCI6MTc0NTgwMjIwNX0.XZa4qMf_kQ99uxgPrm6ADCSebqDFtDF4DUj7DiM0soc

### modificar un usuario (PUT - idempotente, se modifican TODOS los elementos posibles)
PUT http://localhost:3000/api/users/66d8efd9f97ea117d363ce7c
Content-Type: application/json

{
    "firstName": "Abril",
    "lastName": "Carballo",
    "userType": "Waiter"
}


### borrar un user
DELETE http://localhost:3000/api/users/680ecbad207b6b801cb53ca7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVjNWMxMDI2NTZmNTY5ZmNkODYzZCIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDU3OTg2MDUsImV4cCI6MTc0NTgwMjIwNX0.XZa4qMf_kQ99uxgPrm6ADCSebqDFtDF4DUj7DiM0soc

