### obtener todos los shipmentTypes
GET http://localhost:3000/api/shipmentTypes
### obtengo un shipmentType especifico
GET http://localhost:3000/api/shipmentTypes/66db908dfd8f25c9cfba771e
### crear un nuevo shipmentType
POST http://localhost:3000/api/shipmentTypes
Content-Type: application/json

{
    "estimatedTime": 0,
    "type": "Other"
}

### modificar un usuario (PUT - idempotente, se modifican TODOS los elementos posibles)
PUT http://localhost:3000/api/shipmentTypes/66db908dfd8f25c9cfba771e
Content-Type: application/json

{
    "estimatedTime": 30,
    "type": "Cantaberta"
}


### borrar un shipmentTypes
DELETE http://localhost:3000/api/shipmentTypes/66db9094fd8f25c9cfba771f

