### crear cart
POST http://localhost:3000/api/carts
Content-Type: application/json

{
  "user": "672d4f8bb48ca087afa73e85",
  "total": 0
}
### update
PUT http://localhost:3000/api/carts/6813c7c454cffed0b6498cd2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDYxMjk5MTMsImV4cCI6MTc0NjEzMzUxM30.sNu_A5z7IC3IHZ0Whtk-brpPgWNkQ5PzSLpmkxG0ZD8

{"state": "Pending"}

### get all carts
GET http://localhost:3000/api/carts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGNjMzY4NzM5NGE2YzIxNjkzMGU1NiIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NTQ1MTk4NjYsImV4cCI6MTc1NDUyMzQ2Nn0.ddx3e6TsUA_Xoy2Dib77dbP3YR9DrM0eClLzo6h1twY

### delete
DELETE http://localhost:3000/api/carts/6809bfe531bd4eb1258c33f0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDgwZWQ1ZDZkM2UxM2U0NGVhODU4YSIsInVzZXJUeXBlIjoiQ2xpZW50ZSIsImlhdCI6MTc0NTg3NDkyOSwiZXhwIjoxNzQ1ODc4NTI5fQ.1CsaJ1Mm8wQTEbHLCGA4idLANkTLdxQ5JFEYCXaAJJM



