### obtener todos los products
GET http://localhost:3000/api/products


### crear un nuevo user
# @name createUser
POST http://localhost:3000/api/products
Content-Type: application/json

{ 
"name": "Helado",
"price": 4000,
"description": "Tres bolas de helado, servidas en tu sabor favorito, la manera perfecta de refrescarte.", 
"category": "672d4b4cdda5ebf5cf0b7e6e"
}
### ID 
@id = {{createUser.response.body.data.id}}
### obtengo un user especifico
GET http://localhost:3000/api/products/{{id}}

### modificar un usuario (PUT - idempotente, se modifican TODOS los elementos posibles)
PUT http://localhost:3000/api/products/672d4c554a0fac5888ae18ed
Content-Type: application/json

{
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29jYWNvbGF8ZW58MHx8MHx8fDA%3D"
}


### borrar un user
DELETE http://localhost:3000/api/products/66da3a6f4b62e2f444142282

