### obtener todos los products
GET http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGNjMzY4NzM5NGE2YzIxNjkzMGU1NiIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NTQ1MDcxMDksImV4cCI6MTc1NDUxMDcwOX0.FOc5_NXfr6eqEmjoHfLMa5b4IQlW3JB6RIndZJ_368k



### crear un nuevo user
# @name createUser
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDU4NzUyMjIsImV4cCI6MTc0NTg3ODgyMn0.gQtae98rWCrhfhKbH8qEPAycs49avF8yZZGgPwGzohI


{ 
"name": "Pure Smtegasheado",
"price": 200,
"stock": 50,
"description": "Pure de papas, batatas o mixto", 
"category": "66d9c449c530dbc8f754f452",
"img_url": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fcelestedistribuidora.mitiendanube.com%2Fproductos%2Fcoca-cola-500ml-pack-x-12%2F&psig=AOvVaw3SfK0CpmF6ntLSeN9-cVi4&ust=1745330854313000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOiyx6im6YwDFQAAAAAdAAAAABAE",
"state": "Active"
}
### ID 
@id = {{createUser.response.body.data.id}}
### obtengo un user especifico
GET http://localhost:3000/api/products/6888ee9e100e23eeefc8cc15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc0NTc4OTI1NiwiZXhwIjoxNzQ1NzkyODU2fQ.mBJkdmJxQXh70dboWghG1eMq4N7aapvX0ciqsnMBEE8

### modificar un usuario (PUT - idempotente, se modifican TODOS los elementos posibles)
PUT http://localhost:3000/api/products/6888ee9e100e23eeefc8cc15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODY1ZWFjODMwMjJhMjM0NTFmODllYiIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NTM4MDU2MzEsImV4cCI6MTc1MzgwOTIzMX0.FgA15_fzfGXTlrWborwdtdVfmh2yliApm0sugzZUQ8o

{
  "name": "Remolacha",
  "price": 1000,
  "stock": 10,
  "description": "La mejor del mundo",
  "category": "672d4b36dda5ebf5cf0b7e6c",
  "imageUrl": "https://i.pinimg.com/736x/1c/59/8d/1c598d69cf8777658b7f670a884c78c3.jpg",
  "state": "Active"
}



### borrar un user
DELETE http://localhost:3000/api/products/680ff67221c2b4cbe5be5fac
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGVhMTEzY2UyNmViZThiOTBmYTc2YyIsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE3NDU4NzUyMjIsImV4cCI6MTc0NTg3ODgyMn0.gQtae98rWCrhfhKbH8qEPAycs49avF8yZZGgPwGzohI


